title: flamingo camp
baseurl: /
url: https://flamingo.camp
markdown: kramdown
sass:
  style: :compressed
  sass_dir: _sass

exclude:
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
